name: CI-ECR-IMAGE-PUSH

on:
  push

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.10
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        id: vars
        run: |
          IMAGE_TAG="flask"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          FULL_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{secrets.ECR_REPOSITORY }}:$IMAGE_TAG"
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
      
      - name: Debug Print
        run: |
         echo "FULL_IMAGE = $FULL_IMAGE"
         echo "${IMAGE_TAG}"
  

      - name: Build Docker image
        run: |
          docker build -t $FULL_IMAGE .

      - name: Push Docker image
        run: |
          docker push $FULL_IMAGE
